// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace VMLbaithi2324.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("VMLbaithi2324.Models.VML850Person", b =>
                {
                    b.Property<int>("VML850ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("VML850Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("VML850SoThich")
                        .HasColumnType("REAL");

                    b.HasKey("VML850ID");

                    b.ToTable("VML850Person");
                });
#pragma warning restore 612, 618
        }
    }
}
